### ISSUE TITLE
Android example not working

### ISSUE THREAD

**Issue by Koxx3** [rnmapbox/maps#2137]
## Environment
- Dev OS: Win 10
- Device : android Pixel 6A

## Steps to reproduce

```
git clone https://github.com/rnmapbox/maps.git
cd maps
cd example
# generate xxxxxxxxxxxxx access tocken with download permission
echo "xxxxx > accesstoken 

npx yarn install
npx yarn start --reset-cache
npx yarn run android
```

## Result
React app fail to start

## Logs 

Now, after new cloning, I executed : 

logcat : 
```
2022-08-17 09:20:31.218 30318-30582/com.rnmapboxglexample W/unknown:ReactContext: initializeMessageQueueThreads() is called.
2022-08-17 09:20:31.219 30318-30582/com.rnmapboxglexample D/SoLoader: libyoga.so not found on /data/data/com.rnmapboxglexample/lib-main
2022-08-17 09:20:31.219 30318-30582/com.rnmapboxglexample D/SoLoader: libyoga.so found on /data/app/~~H5tQSQfpEz3xyzB3KGfnGQ==/com.rnmapboxglexample-gmr_3zhalLskZKlTcidt3g==/lib/arm64
2022-08-17 09:20:31.219 30318-30582/com.rnmapboxglexample D/SoLoader: Not resolving dependencies for libyoga.so
2022-08-17 09:20:31.249 30318-30582/com.rnmapboxglexample I/flipper: flipper: FlipperClient::addPlugin Fresco
2022-08-17 09:20:31.375 30318-30581/com.rnmapboxglexample E/unknown:ReactNative: Exception in native call from JS
    com.facebook.react.devsupport.JSException: Unexpected EOF
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: com.facebook.jni.CppException: Unexpected EOF
    
    no stack
    	... 8 more
2022-08-17 09:20:31.383 30318-30581/com.rnmapboxglexample E/ReactNativeJNI: Attempting to call JS function on a bad application bundle: HMRClient.setup()
2022-08-17 09:20:31.383 30318-30581/com.rnmapboxglexample E/unknown:ReactNative: Exception in native call
    java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: HMRClient.setup()
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
        at java.lang.Thread.run(Thread.java:920)
2022-08-17 09:20:31.384 30318-30581/com.rnmapboxglexample E/ReactNativeJNI: Attempting to call JS function on a bad application bundle: AppRegistry.runApplication()
2022-08-17 09:20:31.385 30318-30581/com.rnmapboxglexample E/unknown:ReactNative: Exception in native call
    java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: AppRegistry.runApplication()
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
        at java.lang.Thread.run(Thread.java:920)
```

**Comment by mfazekas** [comment]
I could not reproduce the issue Pixel 4/API 26. OSX 12.5, android sdk: 33.0.2

**Comment by Koxx3** [comment]
I am gonna try on linux to see if it related to Windows

**Comment by Koxx3** [comment]
still doesn't work on fresh linux install ...
