### ISSUE TITLE
An error occurred while processing the pre-install hook of the Podfile.  undefined method `pre_install' for nil:NilClass

### ISSUE THREAD

**Issue by sdevansh96** [rnmapbox/maps#2145]
Hi,

I am using m1 pro-Mac and getting this error:

**An error occurred while processing the pre-install hook of the Podfile.

undefined method `pre_install' for nil:NilClass**

Pod install is working fine but pre/post scripts are not working.

Podfile:32:in `block (3 levels) in from_ruby'

pre_install do |installer|
    $RNMapboxMaps.pre_install(installer)
  end

Full Error log:

!] An error occurred while processing the pre-install hook of the Podfile.

undefined method `pre_install' for nil:NilClass

/Users/devansh/Desktop/aaa/ios/Podfile:32:in `block (3 levels) in from_ruby'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/podfile.rb:162:in `pre_install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:889:in `run_podfile_pre_install_hook'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:877:in `block in run_podfile_pre_install_hooks'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:149:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:876:in `run_podfile_pre_install_hooks'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:256:in `block in download_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:254:in `download_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:162:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
Couldn't install Pods. Updating the Pods project and trying again...

**Comment by sdevansh96** [comment]
Even Android app also not working:
Error log:

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-mapbox-gl_maps:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-mapbox-gl_maps:debugCompileClasspath'.
   > Could not find com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0.
     Required by:
         project :react-native-mapbox-gl_maps > com.mapbox.mapboxsdk:mapbox-android-sdk:9.1.0

**Comment by mfazekas** [comment]
You might be installing the old package AKA react-native-mapbox-gl/maps but uing the instructions for @rnmapbox/maps

**Comment by sdevansh96** [comment]
Yes,

Don't  : **npm i @react-native-mapbox-gl/maps**
Do : **npm install rnmapbox/maps#main --save**

Fixed.

Thanks

**Comment by Dyachenko022** [comment]
also if you're using correct package version and it's still not working, try adding library with 
yarn add @rnmapbox/maps
or
npm i @rnmapbox/maps --save

**Comment by Ajmal0197** [comment]
Follow these links for v10 proper integration and Usage:
https://dev.to/ajmal_hasan/react-native-mapbox-v10-installation-7ga
https://dev.to/ajmal_hasan/react-native-mapbox-v10-usage-4gbp

**Comment by mfazekas** [comment]
@Ajmal0197 thanks those looks great. One note, for android instruction I'd advise against: `implementation 'com.mapbox.maps:android:10.8.1'` that should be not necessary and can cause issue if we bump that dependency later.

> Follow these links for v10 proper integration and Usage:
> https://dev.to/ajmal_hasan/react-native-mapbox-v10-installation-7ga
> https://dev.to/ajmal_hasan/react-native-mapbox-v10-usage-4gbp

**Comment by Ajmal0197** [comment]
> @Ajmal0197 thanks those looks great. One note, for android instruction I'd advise against: `implementation 'com.mapbox.maps:android:10.8.1'` that should be not necessary and can cause issue if we bump that dependency later.
> 
> > Follow these links for v10 proper integration and Usage:
> > https://dev.to/ajmal_hasan/react-native-mapbox-v10-installation-7ga
> > https://dev.to/ajmal_hasan/react-native-mapbox-v10-usage-4gbp
> 
> 

Thank you will check your suggestion.👍
