### ISSUE TITLE
getting an error in <MGLNetworkConfiguration: 0x600003867030> in iOS while using Mapbox style url and it is working fine in android

### ISSUE THREAD

**Issue by mastercodebegin** [rnmapbox/maps#2207]
## Environment
- Dev OS: [ macos monterey 12.5]

LOG  {"coords": {"accuracy": 5, "altitude": 0, "altitudeAccuracy": -1, "heading": -1, "latitude": 37.33233141, "longitude": -122.0312186, "speed": 0}, "timestamp": 1663001808021.881}
     LOG  {"coords": {"accuracy": 5, "altitude": 0, "altitudeAccuracy": -1, "heading": -1, "latitude": 37.33233141, "longitude": -122.0312186, "speed": 0}, "timestamp": 1663001804021.881}
     LOG  {"coords": {"accuracy": 5, "altitude": 0, "altitudeAccuracy": -1, "heading": -1, "latitude": 37.33233141, "longitude": -122.0312186, "speed": 0}, "timestamp": 1663001808021.881}
     LOG  TRIGEREED
     LOG  ios accuracy---------- granted
     LOG  {"coords": {"accuracy": 5, "altitude": 0, "altitudeAccuracy": -1, "heading": -1, "latitude": 37.33233141, "longitude": -122.0312186, "speed": 0}, "timestamp": 1663001808021.881}
     LOG  {"coords": {"accuracy": 5, "altitude": 0, "altitudeAccuracy": -1, "heading": -1, "latitude": 37.33233141, "longitude": -122.0312186, "speed": 0}, "timestamp": 1663001808021.881}
     LOG  {"coords": {"accuracy": 5, "altitude": 0, "altitudeAccuracy": -1, "heading": -1, "latitude": 37.33233141, "longitude": -122.0312186, "speed": 0}, "timestamp": 1663001816752.897}
     WARN  Possible Unhandled Promise Rejection (id: 0):
    Error: You should only call this method on Android!
    Error: You should only call this method on Android!
        at requestAndroidLocationPermissions$ (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:255389:28)
        at call (native)
        at tryCatch (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:24077:23)
        at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:24057:34)
        at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:24108:30)
        at call (native)
        at tryCatch (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:24077:23)
        at invoke (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:24115:30)
        at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:24139:19)
        at tryCallTwo (/Users/distiller/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:61:9)
        at doResolve (/Users/distiller/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:216:25)
        at Promise (/Users/distiller/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:82:14)
        at callInvokeWithMethodAndArg (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:24138:33)
        at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:24143:157)
        at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:24108:30)
        at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:24229:69)
        at requestAndroidLocationPermissions (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:255339:38)
        at _callee$ (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:279117:60)
        at call (native)
        at tryCatch (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:24077:23)
        at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:24057:34)
        at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:24108:30)
        at call (native)
        at tryCatch (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:24077:23)
        at invoke (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:24115:30)
        at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:24139:19)
        at tryCallTwo (/Users/distiller/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:61:9)
        at doResolve (/Users/distiller/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:216:25)
        at Promise (/Users/distiller/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:82:14)
        at callInvokeWithMethodAndArg (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:24138:33)
        at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:24143:157)
        at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:24108:30)
        at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:24229:69)
        at _callee (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:279113:38)
        at tryCallTwo (/Users/distiller/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:61:9)
        at doResolve (/Users/distiller/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:216:25)
        at Promise (/Users/distiller/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:82:14)
        at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:279112:32)
        at loadModuleImplementation (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:290:14)
        at guardedLoadModule (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:171:38)
        at metroRequire (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:98:92)
        at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:278277:112)
        at loadModuleImplementation (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:290:14)
        at guardedLoadModule (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:171:38)
        at metroRequire (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:98:92)
        at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:241672:118)
        at loadModuleImplementation (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:290:14)
        at guardedLoadModule (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:171:38)
        at metroRequire (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:98:92)
        at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:240976:108)
        at loadModuleImplementation (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:290:14)
        at guardedLoadModule (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:171:38)
        at metroRequire (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:98:92)
        at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:128970:107)
        at loadModuleImplementation (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:290:14)
        at guardedLoadModule (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:171:38)
        at metroRequire (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:98:92)
        at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:111254:112)
        at loadModuleImplementation (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:290:14)
        at guardedLoadModule (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:171:38)
        at metroRequire (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:98:92)
        at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:1355:104)
        at loadModuleImplementation (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:290:14)
        at guardedLoadModule (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:163:47)
        at metroRequire (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:98:92)
        at global (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.kliqsocial.kliqDistribution:337785:4)
     ERROR  Mapbox error Requesting: Requesting: %@ failed with error: %@ failed with error: <MGLNetworkConfiguration: 0x600003867030> {"filePath": "-[MGLNetworkConfiguration errorLog:]", "level": "error", "line": 129, "message": "Requesting: Requesting: %@ failed with error: %@ failed with error: <MGLNetworkConfiguration: 0x600003867030>"}
     ERROR  Mapbox error [event]:Setup [code]:-1 [message]:loading style failed: unsupported URL {"filePath": "virtual bool mbgl::MGLCoreLoggingObserver::onRecord(mbgl::EventSeverity, mbgl::Event, int64_t, const std::string &)", "level": "error", "line": 30, "message": "[event]:Setup [code]:-1 [message]:loading style failed: unsupported URL"}
    
    **------------When using styleUrl Getting an Error---------------------------------**
    ![Text](https://snipboard.io/P2RlM4.jpg)
    **----------------------Without style url---------------------------------------------------------**
    
    ![Text](https://snipboard.io/G43MzH.jpg)
    
    ![Text](https://snipboard.io/TMbrOI.jpg)
    ![Text](https://snipboard.io/SPaIEC.jpg)
    ![Text](https://snipboard.io/lCMLmI.jpg)
    ![Text](https://snipboard.io/7j15L2.jpg)
    ![Text](https://snipboard.io/K17ANP.jpg)
    ![Text](https://snipboard.io/bnAuQo.jpg)
    
official document i have followed this document link : https://docs.mapbox.com/ios/maps/guides/install/

**Comment by mfazekas** [comment]
```
You should only call this method on Android!
at requestAndroidLocationPermissions
```

**Comment by mastercodebegin** [comment]
ERROR Mapbox error Requesting: Requesting: %@ failed with error: %@ failed with error: <MGLNetworkConfiguration: 0x600003867030> {"filePath": "-[MGLNetworkConfiguration errorLog:]", "level": "error", "line": 129, "message": "Requesting: Requesting: %@ failed with error: %@ failed with error: <MGLNetworkConfiguration: 0x600003867030>"}
ERROR Mapbox error [event]:Setup [code]:-1 [message]:loading style failed: unsupported URL {"filePath": "virtual bool mbgl::MGLCoreLoggingObserver::onRecord(mbgl::EventSeverity, mbgl::Event, int64_t, const std::string &)", "level": "error", "line": 30, "message": "[event]:Setup [code]:-1 [message]:loading style failed: unsupported URL"}
**----------- this is the mapbox Error i need to resolve this error And i've also remove permission also but still getting the same error------**

**Comment by mfazekas** [comment]
It looks to me you're using the default MapLibre implementation, see our install docs

**Comment by mastercodebegin** [comment]
> It looks to me you're using the default MapLibre implementation, see our install docs

what document should i follow could you please provide link for react native.

**Comment by mastercodebegin** [comment]
> It looks to me you're using the default MapLibre implementation, see our install docs

please reply....
