### ISSUE TITLE
[Bug]: Android v10: Crash when navigating back from mapview

### ISSUE THREAD

**Issue by mmelk** [rnmapbox/maps#2345]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-beta.47

### Standalone component to reproduce

```javascript
// ViewInStackNavigator.tsx

import React from 'react';
import { StyleService, useStyleSheet } from '@ui-kitten/components';
import { View, Dimensions } from 'react-native';
import MapboxGL from '@rnmapbox/maps';

export default ({ navigation }): React.ReactElement => {
	const styles = useStyleSheet(themedStyles);

	return (
		<View style={styles.page}>
			<View style={styles.container2}>
				<MapboxGL.MapView style={styles.map}>
					<MapboxGL.Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
				</MapboxGL.MapView>
			</View>
		</View>
	);
};

const themedStyles = StyleService.create({
	page: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center',
	},
	container2: {
		height: 300,
		width: 300,
	},
	map: {
		flex: 1
	},
});
```

### Observed behavior and steps to reproduce

I have View that contain Map. That view, that I mentioned in the standalone component (ViewInStackNavigator) is in the Stack Navigator. 
```javascript
import React from 'react';

import { createStackNavigator } from '@react-navigation/stack';
// Also all screens that I have imported

import * as strings from '../resources/strings';

const Stack = createStackNavigator();

export const MoreNavigator = (): React.ReactElement => (
	<Stack.Navigator screenOptions={{ headerShown: false }}>
		<Stack.Screen name={strings.pageNames.screen1} component={Screen1} />
		<Stack.Screen name={strings.pageNames.viewInStackNavigator} component={ViewInStackNavigator} />
		<Stack.Screen name={strings.pageNames.screen2} component={Screen2} />
		<Stack.Screen name={strings.pageNames.screen3} component={screen3} />
	</Stack.Navigator>
);
```

**App crashes when I press back button (or back gesture) while zooming to the _centerCoordinate_.**

### Additional links and references

Also see Error
1. From firebase
`com.mapbox.rctmgl.components.camera.RCTMGLCamera$mCameraCallback$1.onAnimationCancel (RCTMGLCamera.kt:112)`

`com.mapbox.rctmgl.components.camera.CameraUpdateItem$run$callback$1.onAnimationCancel (CameraUpdateItem.kt:67)
android.animation.AnimatorSet.cancel (AnimatorSet.java:420)
com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.cancelAnimatorSet (CameraAnimationsPluginImpl.kt:388)
com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.cleanup (CameraAnimationsPluginImpl.kt:168)
com.mapbox.maps.plugin.MapPluginRegistry.onDestroy (MapPluginRegistry.kt:128)
com.mapbox.maps.MapController.onDestroy (MapController.kt:172)
com.mapbox.maps.MapView.onDestroy (MapView.kt:219)
com.mapbox.rctmgl.components.mapview.RCTMGLMapView.onDestroy (RCTMGLMapView.kt:1171)
com.mapbox.maps.plugin.lifecycle.MapboxLifecyclePluginImpl$registerLifecycleObserver$1.onDestroy (MapboxLifecyclePluginImpl.kt:68)`

`Caused by java.lang.NullPointerException
       at com.mapbox.rctmgl.components.camera.RCTMGLCamera$mCameraCallback$1.onAnimationCancel(RCTMGLCamera.kt:112)
       at com.mapbox.rctmgl.components.camera.CameraUpdateItem$run$callback$1.onAnimationCancel(CameraUpdateItem.kt:67)
       at android.animation.AnimatorSet.cancel(AnimatorSet.java:420)
       at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.cancelAnimatorSet(CameraAnimationsPluginImpl.kt:388)
       at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.cleanup(CameraAnimationsPluginImpl.kt:168)
       at com.mapbox.maps.plugin.MapPluginRegistry.onDestroy(MapPluginRegistry.kt:128)
       at com.mapbox.maps.MapController.onDestroy(MapController.kt:172)
       at com.mapbox.maps.MapView.onDestroy(MapView.kt:219)
       at com.mapbox.rctmgl.components.mapview.RCTMGLMapView.onDestroy(RCTMGLMapView.kt:1171)
       at com.mapbox.maps.plugin.lifecycle.MapboxLifecyclePluginImpl$registerLifecycleObserver$1.onDestroy(MapboxLifecyclePluginImpl.kt:68)
       at java.lang.reflect.Method.invoke(Method.java)
       at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:222)
       at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:199)
       at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:190)
       at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:40)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
       at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:284)
       at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:302)
       at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
       at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
       at com.mapbox.maps.plugin.lifecycle.ViewLifecycleOwner.hostingLifecycleObserver$lambda-0(ViewLifecycleOwner.kt:41)
       at com.mapbox.maps.plugin.lifecycle.ViewLifecycleOwner.$r8$lambda$guwZVzYaLKecB0WXeVE3morhNNQ()
       at com.mapbox.maps.plugin.lifecycle.ViewLifecycleOwner$$ExternalSyntheticLambda0.onStateChanged(:2)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
       at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:284)
       at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:302)
       at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
       at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
       at com.mapbox.rctmgl.components.mapview.RCTMGLMapView$onAttachedToWindow$1.handleLifecycleEvent(RCTMGLMapView.kt:1189)
       at com.mapbox.rctmgl.components.mapview.RCTMGLMapView.onDropViewInstance(RCTMGLMapView.kt:1176)
       at com.mapbox.rctmgl.components.mapview.RCTMGLMapViewManager.onDropViewInstance(RCTMGLMapViewManager.kt:73)
       at com.mapbox.rctmgl.components.mapview.RCTMGLMapViewManager.onDropViewInstance(RCTMGLMapViewManager.kt:25)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:635)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:646)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:646)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:646)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:646)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:646)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:646)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:646)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:646)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:646)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:646)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:646)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:499)
       at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:217)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
       at android.view.Choreographer.doCallbacks(Choreographer.java:809)
       at android.view.Choreographer.doFrame(Choreographer.java:740)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8469)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)`

2. From mobile side (this error appeared and shown about 1-2 seconds after crash)
![Screenshot_20221027-151237](https://user-images.githubusercontent.com/108338732/198297171-3577c0d2-9272-4090-9a0f-53cb5cba6564.png)

**Comment by mmelk** [comment]
Can anyone help me?

**Comment by TianFengRL** [comment]
same error

**Comment by binh-vng** [comment]
@mmelk try to set `animationMode='none'` in `<MapboxGL.Camera />`. It's worked for me.

**Comment by saltron85** [comment]
@binh-vng I was having the same error OP was experiencing and somehow I just happen to land on this thread. Your solution worked for me as well. Turns out the zoom effect was causing the app to crash and setting the option to known took care of the issue.

**Comment by saeedghasemi72** [comment]
@binh-vng thanks bro, I have same error and this solution work for me.

**Comment by mfazekas** [comment]
Pls test with current version and report back if you can still reproduce
