### ISSUE TITLE
[Bug]: Error while updating property 'stop' of a view managed by: RCTMGLCamera

### ISSUE THREAD

**Issue by benjamin-beau** [rnmapbox/maps#2653]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

8.5.0

### Standalone component to reproduce

Can't reproduce in standalone.

### Observed behavior and steps to reproduce

App crashes when changing screen from one using the map.

```stacktrace
java.lang.IllegalStateException: Expected NUMBER but was NULL at path $.coordinates[0]
    at com.google.gson.internal.bind.JsonTreeReader.nextDouble(JsonTreeReader.java:211)
    at com.mapbox.geojson.BaseCoordinatesTypeAdapter.readPointList(BaseCoordinatesTypeAdapter.java:77)
    at com.mapbox.geojson.ListOfDoublesCoordinatesTypeAdapter.read(ListOfDoublesCoordinatesTypeAdapter.java:26)
    at com.mapbox.geojson.ListOfDoublesCoordinatesTypeAdapter.read(ListOfDoublesCoordinatesTypeAdapter.java:16)
    at com.mapbox.geojson.BaseGeometryTypeAdapter.readCoordinateContainer(BaseGeometryTypeAdapter.java:121)
    at com.mapbox.geojson.Point$GsonTypeAdapter.read(Point.java:388)
    at com.mapbox.geojson.Point$GsonTypeAdapter.read(Point.java:373)
    at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:285)
    at com.google.gson.typeadapters.RuntimeTypeAdapterFactory$1.read(RuntimeTypeAdapterFactory.java:257)
    at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
    at com.mapbox.geojson.Feature$GsonTypeAdapter.read(Feature.java:625)
    at com.mapbox.geojson.Feature$GsonTypeAdapter.read(Feature.java:497)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
    at com.mapbox.geojson.FeatureCollection$GsonTypeAdapter.read(FeatureCollection.java:376)
    at com.mapbox.geojson.FeatureCollection$GsonTypeAdapter.read(FeatureCollection.java:278)
    at com.google.gson.Gson.fromJson(Gson.java:932)
    at com.google.gson.Gson.fromJson(Gson.java:897)
    at com.google.gson.Gson.fromJson(Gson.java:846)
    at com.google.gson.Gson.fromJson(Gson.java:817)
    at com.mapbox.geojson.FeatureCollection.fromJson(FeatureCollection.java:68)
    at com.mapbox.rctmgl.components.camera.CameraStop.fromReadableMap(CameraStop.java:191)
    at com.mapbox.rctmgl.components.camera.RCTMGLCameraManager.setStop(RCTMGLCameraManager.java:43)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:87)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
    at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:47)
    at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:142)
    at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:93)
    at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
    at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
    at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
    at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
    at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1034)
    at android.view.Choreographer.doCallbacks(Choreographer.java:859)
    at android.view.Choreographer.doFrame(Choreographer.java:790)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1021)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7402)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected NUMBER but was NULL at path $.coordinates[0]
    at com.google.gson.Gson.fromJson(Gson.java:944)
    at com.google.gson.Gson.fromJson(Gson.java:897)
    at com.google.gson.Gson.fromJson(Gson.java:846)
    at com.google.gson.Gson.fromJson(Gson.java:817)
    at com.mapbox.geojson.FeatureCollection.fromJson(FeatureCollection.java:68)
    at com.mapbox.rctmgl.components.camera.CameraStop.fromReadableMap(CameraStop.java:191)
    at com.mapbox.rctmgl.components.camera.RCTMGLCameraManager.setStop(RCTMGLCameraManager.java:43)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:87)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
    at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:47)
    at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:142)
    at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:93)
    at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
    at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
    at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
    at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
    at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1034)
    at android.view.Choreographer.doCallbacks(Choreographer.java:859)
    at android.view.Choreographer.doFrame(Choreographer.java:790)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1021)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7402)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

java.lang.reflect.InvocationTargetException: null
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:87)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
    at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:47)
    at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:142)
    at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:93)
    at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
    at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
    at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
    at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
    at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1034)
    at android.view.Choreographer.doCallbacks(Choreographer.java:859)
    at android.view.Choreographer.doFrame(Choreographer.java:790)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1021)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7402)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'stop' of a view managed by: RCTMGLCamera
    at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:102)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
    at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:47)
    at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:142)
    at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:93)
    at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
    at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
    at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
    at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
    at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1034)
    at android.view.Choreographer.doCallbacks(Choreographer.java:859)
    at android.view.Choreographer.doFrame(Choreographer.java:790)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1021)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7402)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

### Expected behavior

No crash.

### Additional links and references

Additional config for android in `build.gradle`:

```gradle
RNMapboxMapsLibs = { 
            implementation 'com.mapbox.maps:android:10.11.1'
            implementation 'com.mapbox.mapboxsdk:mapbox-sdk-turf:6.10.0'
            implementation 'com.mapbox.mapboxsdk:mapbox-android-telemetry:8.1.5'
        }
```

**Comment by mfazekas** [comment]
@benjamin-beau thanks for the report, what is your version as you wrote `8.5.0` but you're also using RNMapboxMapsLibs that will only work with 10* versions.

Also we no longe look into issues in old versions, so please try with 10. betas.

**Comment by benjamin-beau** [comment]
Issue still exists after updating to latest version [v10.0.0-beta.74](https://github.com/rnmapbox/maps/releases/tag/v10.0.0-beta.74), with default configuration (`RNMapboxMapsVersion` and  `RNMapboxMapsLibs`).

**Comment by bailycase99** [comment]
I am also having this issue with the latest v10 versions, seems to be only occurring on Android.

**Comment by EJ132** [comment]
Anyone have any updates on this yet?
