### ISSUE TITLE
Example build failed (Could not resolve all task dependencies)

### ISSUE THREAD

**Issue by kuchejak** [rnmapbox/maps#2807]
## Environment
- Dev OS: Fedora Linux 37 (Workstation Edition) x86_64

I have cloned the repository and followed all the instructions from https://github.com/rnmapbox/maps/tree/main/example, but the android build always fails for me. I have also added the permissions for gradlew as mentioned here https://github.com/rnmapbox/maps/tree/main/example.

## Run output
```
yarn run v1.22.19
$ yarn react-native run-android --verbose
$ /home/kuchejak/src/rnmapbox/example/node_modules/.bin/react-native run-android --verbose
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1476 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...
debug Running command "cd android && ./gradlew app:installDebug -PreactNativeDevServerPort=8081"

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
6 actionable tasks: 6 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.mapbox.maps:android:10.12.1.
     Required by:
         project :app > project :rctmgl
      > Could not resolve com.mapbox.maps:android:10.12.1.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android/10.12.1/android-10.12.1.pom'.
            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android/10.12.1/android-10.12.1.pom'. Received status code 401 from server: Unauthorized
   > Could not resolve com.mapbox.mapboxsdk:mapbox-sdk-turf:6.10.0.
     Required by:
         project :app > project :rctmgl
      > Could not resolve com.mapbox.mapboxsdk:mapbox-sdk-turf:6.10.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-sdk-turf/6.10.0/mapbox-sdk-turf-6.10.0.pom'.
            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-sdk-turf/6.10.0/mapbox-sdk-turf-6.10.0.pom'. Received status code 401 from server: Unauthorized

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.mapbox.maps:android:10.12.1.
     Required by:
         project :app > project :rctmgl
      > Could not resolve com.mapbox.maps:android:10.12.1.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android/10.12.1/android-10.12.1.pom'.
            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android/10.12.1/android-10.12.1.pom'. Received status code 401 from server: Unauthorized
   > Could not resolve com.mapbox.mapboxsdk:mapbox-sdk-turf:6.10.0.
     Required by:
         project :app > project :rctmgl
      > Could not resolve com.mapbox.mapboxsdk:mapbox-sdk-turf:6.10.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-sdk-turf/6.10.0/mapbox-sdk-turf-6.10.0.pom'.
            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-sdk-turf/6.10.0/mapbox-sdk-turf-6.10.0.pom'. Received status code 401 from server: Unauthorized

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s

    at makeError (/home/kuchejak/src/rnmapbox/example/node_modules/execa/index.js:174:9)
    at /home/kuchejak/src/rnmapbox/example/node_modules/execa/index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (/home/kuchejak/src/rnmapbox/example/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/home/kuchejak/src/rnmapbox/example/node_modules/@react-native-community/cli/build/index.js:192:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mfazekas** [comment]
Updated readme. https://github.com/rnmapbox/maps/blob/main/example/README.md
