### ISSUE TITLE
TypeError: Cannot destructure property 'RNMapboxMapsImpl' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by LucasRomier** [rnmapbox/maps#2868]
## Environment
- Dev OS: Win10

## Steps to reproduce

1. Follow Step 1 using expo: ```npx expo install rnmapbox/maps``` or ```npx expo install rnmapbox/maps#main```
2. This generates the following error: ```TypeError: Cannot destructure property 'RNMapboxMapsImpl' of 'undefined' as it is undefined.```

```sh   
TypeError: Cannot destructure property 'RNMapboxMapsImpl' of 'undefined' as it is undefined.
    at withMapbox (D:\Documents\Personal_Data\Workspaces\External\YoFa\Application\node_modules\@rnmapbox\maps\plugin\build\withMapbox.js:271:31)
    at plugin (D:\Documents\Personal_Data\Workspaces\External\YoFa\Application\node_modules\expo\node_modules\@expo\config-plugins\build\plugins\withRunOnce.js:49:25)
    at withRunOnce (D:\Documents\Personal_Data\Workspaces\External\YoFa\Application\node_modules\expo\node_modules\@expo\config-plugins\build\plugins\withRunOnce.js:37:10)
    at D:\Documents\Personal_Data\Workspaces\External\YoFa\Application\node_modules\expo\node_modules\@expo\config-plugins\build\plugins\withRunOnce.js:48:12
    at withStaticPlugin (D:\Documents\Personal_Data\Workspaces\External\YoFa\Application\node_modules\@expo\config-plugins\build\plugins\withStaticPlugin.js:136:12)
    at D:\Documents\Personal_Data\Workspaces\External\YoFa\Application\node_modules\@expo\config-plugins\build\plugins\withPlugins.js:30:84
    at Array.reduce (<anonymous>)
    at withPlugins (D:\Documents\Personal_Data\Workspaces\External\YoFa\Application\node_modules\@expo\config-plugins\build\plugins\withPlugins.js:30:18)
    at withConfigPlugins (D:\Documents\Personal_Data\Workspaces\External\YoFa\Application\node_modules\@expo\config\build\plugins\withConfigPlugins.js:36:47)
    at fillAndReturnConfig (D:\Documents\Personal_Data\Workspaces\External\YoFa\Application\node_modules\@expo\config\build\Config.js:217:78)
```

**Comment by whoiscarlo** [comment]
For those who need visual examples like myself:

```
// app.json

{
  "expo": {
  "plugins": [
    "expo-router",
    [ <--- brackets
      "@rnmapbox/maps",
      {
        "RNMapboxMapsDownloadToken": "sk.ey..",
        "RNMapboxMapsVersion": "11.0.0"
      }
    ] <--- brackets
  ],
  }
}
```
