### ISSUE TITLE
[Bug]: Enabling Proguard causes a crash when toggling layer visibilty

### ISSUE THREAD

**Issue by jfaq89** [rnmapbox/maps#2895]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.7.0

### Platform

Android

### `@rnmapbox/maps` version

10.0.7

### Relevat code to reproduce crash

```
apply plugin: "com.android.application"
apply plugin: "com.facebook.react"
...


project.ext.envConfigFiles = [
...
]
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"

import com.android.build.OutputFile


react {
 ...
}

def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = true // <- changing this to false solves the problem

def jscFlavor = 'org.webkit:android-jsc:+'

...

android {
    ndkVersion rootProject.ext.ndkVersion

    compileSdkVersion rootProject.ext.compileSdkVersion

    namespace "com.myapliccation.withmaps"
    defaultConfig {
       ...
    }

    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include(*reactNativeArchitectures())
        }
    }
    signingConfigs {
       ...
    }
    flavorDimensions "env"
    productFlavors {
   ...
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
            matchingFallbacks = ['debug', 'release']
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.release

            minifyEnabled enableProguardInReleaseBuilds 
            // Typical pro-guard definitions
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            // Detox-specific additions to pro-guard
            proguardFile "${rootProject.projectDir}/../node_modules/detox/android/detox/proguard-rules-app.pro"

            firebaseCrashlytics {
                nativeSymbolUploadEnabled true
                unstrippedNativeLibsDir 'build/intermediates/merged_native_libs/release/out/lib'
            }
        }
    }

}

dependencies {
   ...
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
```

### Observed behavior and steps to reproduce

If I enable proguard I get a crash when toggling layer visibilty. Here is the stack trace from Crashlytics :

# Crashlytics - Stack trace
Platform: android
Date: Thu Jun 01 2023 14:19:41 GMT+0200 (Central European Summer Time)

```
Fatal Exception: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'reactStyle' of a view managed by: RCTMGLSymbolLayer
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(:120)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(:10)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(:36)
       at com.facebook.react.uimanager.ViewManager.updateProperties(:10)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(:14)
       at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(:10)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(:135)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(:53)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2600()
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(:31)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame()
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(:46)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(:2)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
       at android.view.Choreographer.doCallbacks(Choreographer.java:809)
       at android.view.Choreographer.doFrame(Choreographer.java:740)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

Caused by java.lang.reflect.InvocationTargetException:
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(:54)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(:10)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(:36)
       at com.facebook.react.uimanager.ViewManager.updateProperties(:10)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(:14)
       at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(:10)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(:135)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(:53)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2600()
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(:31)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame()
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(:46)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(:2)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
       at android.view.Choreographer.doCallbacks(Choreographer.java:809)
       at android.view.Choreographer.doFrame(Choreographer.java:740)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

Caused by com.mapbox.maps.MapboxStyleException: Set layer property "icon-rotate" failed:
Layer mapboxUserLocationHeadingIndicator is not in style
0.0
       at com.mapbox.maps.extension.style.layers.Layer.updateProperty(:78)
       at com.mapbox.maps.extension.style.layers.Layer.setProperty$extension_style_release(:16)
       at com.mapbox.maps.extension.style.layers.generated.SymbolLayer.iconRotate(:11)
       at com.mapbox.rctmgl.components.styles.RCTMGLStyleFactory.setIconRotate(RCTMGLStyleFactory.java:21)
       at com.mapbox.rctmgl.components.styles.RCTMGLStyleFactory.setSymbolLayerStyle(RCTMGLStyleFactory.java:1166)
       at com.mapbox.rctmgl.components.styles.layers.RCTMGLSymbolLayer.addStyles(RCTMGLSymbolLayer.java:25)
       at com.mapbox.rctmgl.components.styles.layers.RCTLayer.setReactStyle(RCTLayer.java:6)
       at com.mapbox.rctmgl.components.styles.layers.RCTMGLSymbolLayerManager.setReactStyle(:5)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(:54)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(:10)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(:36)
       at com.facebook.react.uimanager.ViewManager.updateProperties(:10)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(:14)
       at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(:10)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(:135)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(:53)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2600()
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(:31)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame()
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(:46)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(:2)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
       at android.view.Choreographer.doCallbacks(Choreographer.java:809)
       at android.view.Choreographer.doFrame(Choreographer.java:740)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

### Expected behavior

To get the app running normally like when proguard is disabled.

### Notes / preliminary analysis

I tried adding the following proguard rules but it didn't work:

```
-keep class com.mapbox.maps.** { *; }
-keep class com.mapbox.rctmgl.components.styles.layers.** { *; }
```

**Comment by jfaq89** [comment]
We can close it for now, because I cannot reproduce it on a new repo. I think the crash happens when the App is doing too much work (rendering a lot of markers and doing a lot of computation processes at the same time), but it is hard to bring a fresh repo to the level of complexity of our current app.
