### ISSUE TITLE
[Bug]: Existing layers when the map is offline

### ISSUE THREAD

**Issue by orca-nazar** [rnmapbox/maps#3152]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.16.1

### Platform

Android

### `@rnmapbox/maps` version

#main

### Standalone component to reproduce

```javascript
import Mapbox, { Camera, MapView } from '@rnmapbox/maps';
import React, { useState } from 'react';
import { Button } from 'react-native';

const getStyles = (isDark) => ({
  mapView: { flex: 1 },
  overlay: {
    fillColor: isDark ? 'hsl(76,26%,75%)' : 'hsl(200,46%,69%)',
  },
});

const { Dark, Light } = Mapbox.StyleURL;

const BugReportExample = () => {
  const [styleUrl, setStyleUrl] = useState(Light);
  const isDark = styleUrl === Dark;
  const buttonTitle = isDark ? 'Set Light' : 'Set Dark';
  const styles = getStyles(isDark);

  return (
    <>
      <Button
        title={buttonTitle}
        onPress={() => setStyleUrl(isDark ? Light : Dark)}
      />
      <MapView style={styles.mapView} styleURL={styleUrl}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <Mapbox.VectorSource id="composite">
          <Mapbox.FillLayer
            id="national-park"
            sourceLayerID="landuse_overlay"
            sourceID="composite"
            style={styles.overlay}
          />
        </Mapbox.VectorSource>
      </MapView>
    </>
  );
};

export default BugReportExample;

```

### Observed behavior and steps to reproduce

In our app we experience this issue when styles are switched in 2 scenarios
1. Fast switching between dark and satellite mode (can't reproduce it in Example app). Our workaround is to apply(mount) custom sources and layers only after `onDidFinishLoadingMap` is fired
2. In offline mode between switching dark and light mode

The second scenario could be reproducable by using BugReportExample
1. In online mode open Bug Report Template TS
2. Go Offline 
3. Switch to Dark mode. Dark styles will be missed as no connection
4. Switch back to Light mode. 
Actual result: `Error while updating property 'reactStyle' of a view managed by: RNMBXFillLayer
null
Set layer property "fill-color" failed:
Layer national-park is not in style:`

### Expected behavior

No issues

### Notes / preliminary analysis

It happens only when color is dynamically changed:
`fillColor: isDark ? 'hsl(76,26%,75%)' : 'hsl(200,46%,69%)',`
No issues in this case: 
`fillColor:  'hsl(76,26%,75%)'`

**Comment by bviebahn** [comment]
I got some similar errors when changing the styleURL. This one seems to be caused by the compass:
```
Error while updating property 'reactStyle' of a view managed by: RCTMGLSymbolLayer
...
Caused by com.mapbox.maps.MapboxStyleException: Set layer property "icon-rotate" failed:
Layer mapboxUserLocationHeadingIndicator is not in style
159.71372985839844
       at com.mapbox.maps.extension.style.layers.Layer.updateProperty(Layer.kt:152)
       at com.mapbox.maps.extension.style.layers.Layer.setProperty$extension_style_publicRelease(Layer.kt:141)
       at com.mapbox.maps.extension.style.layers.generated.SymbolLayer.iconRotate(SymbolLayer.kt:809)
       at com.mapbox.rctmgl.components.styles.RCTMGLStyleFactory.setIconRotate(RCTMGLStyleFactory.java:1318)
       at com.mapbox.rctmgl.components.styles.RCTMGLStyleFactory.setSymbolLayerStyle(RCTMGLStyleFactory.java:255)
       at com.mapbox.rctmgl.components.styles.layers.RCTMGLSymbolLayer.addStyles(RCTMGLSymbolLayer.kt:31)
       at com.mapbox.rctmgl.components.styles.layers.RCTLayer.setReactStyle(RCTLayer.kt:124)
       at com.mapbox.rctmgl.components.styles.layers.RCTMGLSymbolLayerManager.setReactStyle(RCTMGLSymbolLayerManager.kt:60)
       at java.lang.reflect.Method.invoke(Method.java)
       ...
```

**Comment by mfazekas** [comment]
![image](https://github.com/rnmapbox/maps/assets/52435/5e64ced6-30b1-49d8-8081-af3a0262dedb)


I don't see this warning on main.

I've needed to add existing flags for the source and layer as those were referring to existing layers in the style:

```jsx
/*
import React from 'react';
import { Button } from 'react-native';
import {
  Images,
  MapView,
  ShapeSource,
  SymbolLayer,
  CircleLayer,
  Camera,
} from '@rnmapbox/maps';

const styles = {
  mapView: { flex: 1 },
  circleLayer: {
    circleRadiusTransition: { duration: 5000, delay: 0 },
    circleColor: '#ff0000',
  },
};

const features = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      id: 'a-feature',
      properties: {
        icon: 'example',
        text: 'example-icon-and-label',
      },
      geometry: {
        type: 'Point',
        coordinates: [-74.00597, 40.71427],
      },
    },
    {
      type: 'Feature',
      id: 'b-feature',
      properties: {
        text: 'just-label',
      },
      geometry: {
        type: 'Point',
        coordinates: [-74.001097, 40.71527],
      },
    },
    {
      type: 'Feature',
      id: 'c-feature',
      properties: {
        icon: 'example',
      },
      geometry: {
        type: 'Point',
        coordinates: [-74.00697, 40.72427],
      },
    },
  ],
};

class BugReportExample extends React.Component {
  state = {
    radius: 20,
  };

  render() {
    const circleLayerStyle = {
      ...styles.circleLayer,
      ...{ circleRadius: this.state.radius },
    };

    return (
      <>
        <Button
          title="Grow"
          onPress={() => this.setState({ radius: this.state.radius + 20 })}
        />
        <MapView style={styles.mapView}>
          <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
          <Images images={{ example: require('../assets/example.png') }} />
          <ShapeSource id={'shape-source-id-0'} shape={features}>
            <CircleLayer id={'circle-layer'} style={circleLayerStyle} />
            <SymbolLayer
              id="symbol-id"
              style={{
                iconImage: ['get', 'icon'],
              }}
            />
          </ShapeSource>
        </MapView>
      </>
    );
  }
}

export default BugReportExample;
*/

import Mapbox, { Camera, MapView } from '@rnmapbox/maps';
import React, { useState } from 'react';
import { Button } from 'react-native';

const getStyles = (isDark) => ({
  mapView: { flex: 1 },
  overlay: {
    fillColor: isDark ? 'hsl(76,26%,75%)' : 'hsl(200,46%,69%)',
  },
});

const { Dark, Light } = Mapbox.StyleURL;

const BugReportExample = () => {
  const [styleUrl, setStyleUrl] = useState(Light);
  const isDark = styleUrl === Dark;
  const buttonTitle = isDark ? 'Set Light' : 'Set Dark';
  const styles = getStyles(isDark);

  return (
    <>
      <Button
        title={buttonTitle}
        onPress={() => setStyleUrl(isDark ? Light : Dark)}
      />
      <MapView style={styles.mapView} styleURL={styleUrl}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <Mapbox.VectorSource id="composite" existing>
          <Mapbox.FillLayer
            id="national-park"
            sourceLayerID="landuse_overlay"
            sourceID="composite"
            existing
            style={styles.overlay}
          />
        </Mapbox.VectorSource>
      </MapView>
    </>
  );
};

export default BugReportExample;

```

**Comment by orca-nazar** [comment]
@mfazekas It always reproduces even with `existing` property. 
The problem is the next: once the new styles are applied, all features will be removed from map including "existing", but the logic to recreate them doesn't exist. Should not they be skipped, as creating/deleting "existing" features should be handled by mapbox itself

**Comment by mfazekas** [comment]
> @mfazekas It always reproduces even with `existing` property.
> The problem is the next: once the new styles are applied, all features will be removed from map including "existing", but the logic to recreate them doesn't exist. Should not they be skipped, as creating/deleting "existing" features should be handled by mapbox itself

@orca-nazar can you be please more specific. Which @rnmapbox/maps version have you tested with , which component you've tried? The one in my comment? - https://github.com/rnmapbox/maps/issues/3152#issuecomment-1810898667

**Comment by orca-nazar** [comment]
Correct, I use the latest version and your component

**Comment by mfazekas** [comment]
@orca-nazar I don't see the issue on current #main.

```jsx
import Mapbox, { Camera, MapView } from '@rnmapbox/maps';
import React, { useState } from 'react';
import { Button } from 'react-native';

const getStyles = (isDark) => ({
  mapView: { flex: 1 },
  overlay: {
    fillColor: isDark ? 'hsl(76,26%,75%)' : 'hsl(200,46%,69%)',
  },
});

const { Dark, Light } = Mapbox.StyleURL;

const BugReportExample = () => {
  const [styleUrl, setStyleUrl] = useState(Light);
  const isDark = styleUrl === Dark;
  const buttonTitle = isDark ? 'Set Light' : 'Set Dark';
  const styles = getStyles(isDark);

  return (
    <>
      <Button
        title={buttonTitle}
        onPress={() => setStyleUrl(isDark ? Light : Dark)}
      />
      <MapView style={styles.mapView} styleURL={styleUrl}>
        <Camera
          defaultSettings={{
            centerCoordinate: [-74.00597, 40.71427],
            zoomLevel: 8,
          }}
        />
        <Mapbox.VectorSource id="composite" existing>
          <Mapbox.FillLayer
            id="national-park"
            sourceLayerID="landuse_overlay"
            sourceID="composite"
            existing
            style={styles.overlay}
          />
        </Mapbox.VectorSource>
      </MapView>
    </>
  );
};

export default BugReportExample;
```
https://github.com/rnmapbox/maps/assets/52435/4aa3d02e-8064-44d5-95a0-612805cec2e6

**Comment by orca-nazar** [comment]
Please check the steps to reproduce, the main point here was to go to offline mode.
But before it, you need to clear the map data. You can go to app settings and clear data storage or delete/install the app.  Then please follow the steps in the [video](https://drive.google.com/file/d/1srRNbfU6QEiwLFsIPuLo_ipweJUVgSkl/view?usp=sharing).
Thanks :)

**Comment by mfazekas** [comment]
I think we need to add a check that if component is declared `mExisitng` but layer doesn't `exists` then we need to defer adding the layer until it's available, ideally we can use `mapView.waitForLayer(` for that.


https://github.com/rnmapbox/maps/blob/12946ef74f3fe98e9bf967c7ea46049a5a3e1e2c/android/src/main/java/com/rnmapbox/rnmbx/components/styles/layers/RNMBXLayer.kt#L286-L299

**Comment by orca-nazar** [comment]
Sound good. Also, I'm wondering if this technique can be useful for the next case:
> Fast switching between dark and satellite mode (can't reproduce it in Example app). Our workaround is to apply(mount) custom sources and layers only after onDidFinishLoadingMap is fired

So it could applied to filters and styles props updates

**Comment by jnocz** [comment]
Hi, any updates on this issue? Thank you
