### ISSUE TITLE
[Bug]: Exception in ViewTagResolver after app reloading

### ISSUE THREAD

**Issue by orca-nazar** [rnmapbox/maps#3243]
### Mapbox Implementation

Mapbox

### Mapbox Version

10.16.2

### Platform

Android

### `@rnmapbox/maps` version

#main

### Standalone component to reproduce

```javascript
// I could not reproduce it in the Example app 
export default () => {};

```

### Observed behavior and steps to reproduce

The issue occurs after hot reloading or reloading via terminal in debug mode. To avoid it only helps full(force) closing the app

### Expected behavior

No issues

### Notes / preliminary analysis

Looks like making the manager optional and adding guards when extracting it, solves the problem
```
private val manager : UIManager?
        get() =
            if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
                UIManagerHelper.getUIManager(context, UIManagerType.FABRIC)
            } else {
                UIManagerHelper.getUIManager(context, UIManagerType.DEFAULT)
            }
```

### Additional links and references

![screencap-2023-12-06T073217 785Z](https://github.com/rnmapbox/maps/assets/105058015/27a13f9a-3025-44b4-b9e7-930621b48cb7)

**Comment by orca-nazar** [comment]
> > Looks like making the manager optional and adding guards when extracting it, solves the problem
> 
> Not solves just hides the issue. Without view tag resolver we will not be able to call methods on the components like `MapView#getCenter`.
Yes, I see. Maybe there is a way to avoid red screens, when exception occurs

**Comment by orca-nazar** [comment]
@mfazekas If we move out viewWaiters from catch and handle it in try block. Do you think it might work for all cases?
```
    fun <V>withViewResolved(viewTag: Int, reject: Promise? = null, fn: (V) -> Unit) {
        context.runOnUiQueueThread() {
            try {
                val view = manager?.resolveView(viewTag) as V

                if (view == null && !createdViews.contains(viewTag)) {
                    viewWaiters.getOrPut(viewTag) { mutableListOf<ViewTagWaiter<View>>() }.add(ViewTagWaiter<View>({ view -> fn(view as V) }, reject))
                } else if (view == null && createdViews.contains(viewTag)) {
                    reject?.reject(Exception("No view"))
                } else {
                    fn(view)
                }
            } catch (err: Exception) {
                reject?.reject(err)
            }
        }
    }

**Comment by mfazekas** [comment]
So the crash is coming from 

```kotlin
                UIManagerHelper.getUIManager(context, UIManagerType.DEFAULT)!!
```

And we need that UI manager for finding the native views for viewTag. (JS side passes methods with viewTags and we need to find the native view using the viewTag.)

Does it say anything int the logcat? Which RN version do you use?

**Comment by orca-nazar** [comment]
RN: 0.71.8
On initial loading UI manager is available, however `IllegalViewOperationException` is thrown (it's covered by catch block). After reloading either via metro bundler or RN context menu, the `manager` becomes `null` and `createdViews` are not empty. So it goes to this condition: `reject?.reject(Exception("No view"))`. Actually, it should be another message here

**Comment by WoLewicki** [comment]
IIRC for some reason after refresh, the catalyst instance is not present and this check fails: https://github.com/facebook/react-native/blob/31005b7fd9a9579920b55f921c477a90fb3f6d10/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ReactContext.java#L240 when calling `                UIManagerHelper.getUIManager(context, UIManagerType.FABRIC)!!` (at least on new arch). It would be nice to find out why it happens and if we are doing something wrong.

**Comment by mfazekas** [comment]
@WoLewicki do you see it on new arch? In 0.73?

**Comment by mfazekas** [comment]
Yep I see it on our example app. But for me react-navigation also doesn't works after a refresh. Does refresh works if @rnmapbox/maps not installed?

@orca-nazar do you also have the new arch enabled?


```logcat
2023-12-08 17:35:28.365 19202-19202 unknown:Vi...rtyUpdater com.rnmapboxglexample                W  Could not find generated setter for class com.facebook.react.uimanager.RootViewManager
2023-12-08 17:35:28.370 19202-19202 unknown:co...agerHelper com.rnmapboxglexample                E  Unhandled SoftException
                                                                                                    com.facebook.react.bridge.ReactNoCrashSoftException: Cannot get UIManager because the context doesn't contain an active CatalystInstance.
                                                                                                    	at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:77)
                                                                                                    	at com.facebook.react.uimanager.UIManagerHelper.getEventDispatcher(UIManagerHelper.java:128)
                                                                                                    	at com.facebook.react.uimanager.UIManagerHelper.getEventDispatcherForReactTag(UIManagerHelper.java:106)
                                                                                                    	at com.th3rdwave.safeareacontext.SafeAreaProviderManagerKt.handleOnInsetsChange(SafeAreaProviderManager.kt:39)
                                                                                                    	at com.th3rdwave.safeareacontext.SafeAreaProviderManagerKt.access$handleOnInsetsChange(SafeAreaProviderManager.kt:1)
                                                                                                    	at com.th3rdwave.safeareacontext.SafeAreaProviderManager$addEventEmitters$1.invoke(SafeAreaProviderManager.kt:28)
                                                                                                    	at com.th3rdwave.safeareacontext.SafeAreaProviderManager$addEventEmitters$1.invoke(SafeAreaProviderManager.kt:28)
                                                                                                    	at com.th3rdwave.safeareacontext.SafeAreaProvider.maybeUpdateInsets(SafeAreaProvider.kt:21)
                                                                                        
```

**Comment by orca-nazar** [comment]
Nope, the error happens here `UIManagerHelper.getUIManager(context, UIManagerType.DEFAULT)`

**Comment by mfazekas** [comment]
FWIW For the Fabric issues on reload went away for me since I've update reps in our example app. (I've upgraded react-native-safe-area-context and react-native-screens and removed react-native-svg https://github.com/rnmapbox/maps/pull/3257/files) But I'm not 100% if that this is the solution of the issue for the fabric case.

**Comment by WoLewicki** [comment]
Hmm I am afraid it is something we would want to fix upstream in the RN core, since we use methods from the `UIManagerHelper` and they fail. cc @cortinico are you aware of such issue, the catalyst instance being not present after resfresh of the app? Or maybe we are using it in the wrong way?

**Comment by dpyeates** [comment]
I'm seeing this as well in my production apps. First load works OK, but if you put the app into the background and then bring it back active I get an Exception in Native call from JS in ViewTagResolver.kt:51.

**Comment by dpyeates** [comment]
Any update on this? I know its a quiet time of year with Christmas and New Year but I'm getting multiple daily emails from users saying my application runs fine the first time after installation but every subsequent start the app crashes straight away.

Big thanks to all and Happy New Year everyone.

**Comment by mfazekas** [comment]
@dpyeates no I had not looked into this issue nor do I plan to. I cannot reproduce the issue in development (with or without fabric), so it would be very hard for me to do so.

What I suggest you to do. Assumption: the reload in debug issue relates to production, and you can repro the issue in your debug build.
1.) Simplify your MapView usage to see if you can still repro the issue (ideally you just replace your App.js with a simple <MapView component>)
2.) Try to reproduce the issue on a blank rn project (created with `npx react-native@0.71.8 init AwesomeProject --version  0.71.8`
If you cannot, then add packages you're using to the blank project.

**Comment by VolkerLieber** [comment]
It seems to be reproducible for me by calling
`
import ExpoUpdates from "expo-updates/src/ExpoUpdates";
ExpoUpdates.reload();
`

I'll look into it if I find some time, because it screws up our hotfix procedure, but maybe this helps you reproduce the issue on your side.

**Comment by mfazekas** [comment]
@VolkerLieber so you're using rnmapbox then applying expo update, then try to use rnmapbox again?

```jsx
import {
  reloadAsync,
} from 'expo-updates'
```

It's kind of a tricky situation. And I can image some code is @rnmapbox/maps is not prepared for this, because normally this doesn't happen.

(FWIW Even current expo has issue with applying update in the middle of an app run: https://github.com/expo/expo/issues/32073)

**Comment by VolkerLieber** [comment]
@mfazekas The update is requested on startup, the reload is triggered after download. At this point, the map screen should probably not be loaded, because we wait until the whole update procedure before we continue.

Good find with expo notifications :smile:

**Comment by SamuelBrucksch** [comment]
I also debugged this a bit, and adding the second catch to the existing catch at least prevents the crash (in file java/com/rnmapbox/rnmbx/utils/ViewTagResolver.kt)
```
            } catch (err: IllegalViewOperationException) {
                if (!createdViews.contains(viewTag)) {
                    viewWaiters.getOrPut(viewTag) { mutableListOf<ViewTagWaiter<View>>() }.add(ViewTagWaiter<View>({ view -> fn(view as V) }, reject))
                } else {
                    reject?.reject(err)
                }
            } catch (err: Exception) {
                reject?.reject(err)
            }
```

The error comes from `java/com/rnmapbox/rnmbx/components/mapview/NativeMapViewModule.kt`:
https://github.com/rnmapbox/maps/blob/fa80ae549a65d8473cd731f79f57a65fcc9c9fbc/android/src/main/java/com/rnmapbox/rnmbx/components/mapview/NativeMapViewModule.kt#L25

This line exactly.

My uneducated guess is, that during a reload the components do not get properly unloaded, the mapref stays defined due to that, and we never get into the 
```
        if (viewRef == null) {
            reject.reject(Exception("viewRef is null"))
        } else {
            viewTagResolver.withViewResolved(viewRef.toInt(), reject, fn)
        }
```
viewRef = null logic due to that which would prevent the resolver from being called.

So my guess is we could prevent this on JS side eventually already, by setting the mapref to null somehow. Any idea on how to do that? If that is not possible the native side probably would have to check for it...

**Comment by SamuelBrucksch** [comment]
Here is another possible working solution:
```
private val manager : UIManager?
        get() =
            if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
                UIManagerHelper.getUIManager(context, UIManagerType.FABRIC)
            } else {
                UIManagerHelper.getUIManager(context, UIManagerType.DEFAULT)
            }

    // calls on UiQueueThread with resolved view
    fun <V>withViewResolved(viewTag: Int, reject: Promise? = null, fn: (V) -> Unit) {
        context.runOnUiQueueThread() {
            try {
                val resolvedView: View? = manager?.resolveView(viewTag)
                val view = resolvedView as? V
                if (view != null) {
                    fn(view)
                } else {
                    Logger.e(LOG_TAG, "view: $resolvedView found with tag: $viewTag but it's either null or not the correct type")
                    reject?.reject(Throwable("view: $resolvedView found with tag: $viewTag but it's either null or not the correct type"))
                }
            } catch (err: IllegalViewOperationException) {
                if (!createdViews.contains(viewTag)) {
                    viewWaiters.getOrPut(viewTag) { mutableListOf<ViewTagWaiter<View>>() }.add(ViewTagWaiter<View>({ view -> fn(view as V) }, reject))
                } else {
                    reject?.reject(err)
                }
            }
        }
    }
```
Please note that `private val manager : UIManager?` now is nullable, so the check 
```
                val resolvedView: View? = manager?.resolveView(viewTag)
                val view = resolvedView as? V
                if (view != null) {
                    fn(view)
                } else {
                    Logger.e(LOG_TAG, "view: $resolvedView found with tag: $viewTag but it's either null or not the correct type")
                    reject?.reject(Throwable("view: $resolvedView found with tag: $viewTag but it's either null or not the correct type"))
                }
```
already works properly, if the view manager is null. it could be made a bit better, to print an error, that the manager is not available, but it's only for reloading the app which is quite an edge case anyways...

**Comment by konstmar-ion** [comment]
Hello Everyone. Any updates on this issue?

**Comment by mfazekas** [comment]
This is old issue and lot of things changed in RN / rnmapbox. 

 Please reopen with a repro on v10.3+ with new arch enabled.
