### ISSUE TITLE
[Bug]: NullPointerException   com.rnmapbox.rnmbx.utils.ViewTagResolver 

### ISSUE THREAD

**Issue by JClackett** [rnmapbox/maps#3343]
### Mapbox Implementation

Mapbox

### Mapbox Version

11.0.0

### Platform

Android

### `@rnmapbox/maps` version

10.1.5

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

Only when deployed, the app sometimes crashes on android with this:

```
java.lang.NullPointerException: null
    at com.rnmapbox.rnmbx.utils.ViewTagResolver.getManager(ViewTagResolver.kt:51)
    at com.rnmapbox.rnmbx.utils.ViewTagResolver.withViewResolved$lambda$4(ViewTagResolver.kt:58)
    at com.rnmapbox.rnmbx.utils.ViewTagResolver.$r8$lambda$ZFXWzquiK28lSR5tbH0BihabahM
    at com.rnmapbox.rnmbx.utils.ViewTagResolver$$ExternalSyntheticLambda0.run
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8757)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### Expected behavior

Not crash

### Notes / preliminary analysis

Really not sure, after the app crashed and reopening it works again

**Comment by mfazekas** [comment]
See https://github.com/rnmapbox/maps/issues/3243, can't really do much with it without a way to reproduce the issue

**Comment by jacobhummel** [comment]
@mfazekas We started seeing this issue a lot in production after upgrading Expo 48 -> 49 and `@rnmapbox/maps` 10.0.10 -> 10.1.8 simultaneously (so I can't say 100% it's just the mapbox change). Our app crash rate went from under 2% to around 8% from this one crash. It seems to intermittently occur when a user is using the app for a while in the background and re-opens it. It crashes immediately on app re-open.

**Comment by gretzky** [comment]
We're experiencing the same issue. While it's very hard to reproduce- it seems like [this issue is related](https://github.com/facebook/react-native/issues/43692).

**Comment by FrederickEngelhardt** [comment]
Google shows it on a Motorola api 30

![Screenshot_20240809_172332_Chrome.jpg](https://github.com/user-attachments/assets/1ae0002e-7a6f-4c86-8bd8-dffc75f0c867)



FATAL EXCEPTION: main
Process: <yourapp>, PID: 19862
java.lang.NullPointerException
	at com.rnmapbox.rnmbx.components.mapview.y.H0(SourceFile:27)
	at com.rnmapbox.rnmbx.components.mapview.NativeMapViewModule$n.a(SourceFile:12)
	at com.rnmapbox.rnmbx.components.mapview.NativeMapViewModule$n.invoke(SourceFile:3)
	at ha.r.h(SourceFile:34)
	at ha.r.a(SourceFile:1)
	at ha.p.run(SourceFile:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:1)
	at android.os.Looper.loop(Looper.java:240)
	at android.app.ActivityThread.main(ActivityThread.java:8000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by Gp2mv3** [comment]
Hello,
I see the same error in my Android vitals.
I'm using RN 0.74.0 and rnMapbox 10.1.29.

Maybe this trace can help too:
```
Exception java.lang.NullPointerException:
  at com.rnmapbox.rnmbx.components.camera.CameraUpdateQueue.execute (CameraUpdateQueue.kt:62)
  at com.rnmapbox.rnmbx.components.camera.RNMBXCamera.updateCamera (RNMBXCamera.kt:205)
  at com.rnmapbox.rnmbx.components.camera.RNMBXCamera.access$setHasSentFirstRegion$p (RNMBXCamera.kt:41)
  at com.rnmapbox.rnmbx.components.camera.RNMBXCamera.access$updateCamera (RNMBXCamera.kt:41)
  at com.rnmapbox.rnmbx.components.camera.RNMBXCamera$addToMap$1.invoke (RNMBXCamera.kt:104)
  at com.rnmapbox.rnmbx.components.camera.RNMBXCamera$addToMap$1.invoke (RNMBXCamera.kt:101)
  at com.rnmapbox.rnmbx.components.mapview.RNMBXLifeCycle.afterAttachFromLooper (RNMBXMapView.kt:178)
  at com.rnmapbox.rnmbx.components.mapview.RNMBXMapView.onAttachedToWindow$lambda$26 (RNMBXMapView.kt:1479)
  at android.os.Handler.handleCallback (Handler.java:958)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:230)
  at android.os.Looper.loop (Looper.java:319)
  at android.app.ActivityThread.main (ActivityThread.java:8918)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:608)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1103)
```


Any clue ?

**Comment by nixolas1** [comment]
We're getting it on Expo 51, RN 0.74.5,   "@rnmapbox/maps": "^10.1.31", RNMapboxMapsVersion: "11.6.0",
When the app initializes, in with devserver. Often 50% chance when reloading app from dev server.

> 09-25 10:24:33.201 22341 22341 E DevLauncher: Exception in native call from JS
09-25 10:24:33.201 22341 22341 E DevLauncher: java.lang.NullPointerException
09-25 10:24:33.201 22341 22341 E DevLauncher: 	at com.rnmapbox.rnmbx.utils.ViewTagResolver.getManager(ViewTagResolver.kt:54)
09-25 10:24:33.201 22341 22341 E DevLauncher: 	at com.rnmapbox.rnmbx.utils.ViewTagResolver.tagAssigned$lambda$2(ViewTagResolver.kt:33)
09-25 10:24:33.201 22341 22341 E DevLauncher: 	at com.rnmapbox.rnmbx.utils.ViewTagResolver.$r8$lambda$fFgiZ0J-rbxO4IwNPQ2Xls8C8z4(Unknown Source:0)
09-25 10:24:33.201 22341 22341 E DevLauncher: 	at com.rnmapbox.rnmbx.utils.ViewTagResolver$$ExternalSyntheticLambda1.run(Unknown Source:6)
09-25 10:24:33.201 22341 22341 E DevLauncher: 	at android.os.Handler.handleCallback(Handler.java:958)
09-25 10:24:33.201 22341 22341 E DevLauncher: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-25 10:24:33.201 22341 22341 E DevLauncher: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
09-25 10:24:33.201 22341 22341 E DevLauncher: 	at android.os.Looper.loopOnce(Looper.java:230)
09-25 10:24:33.201 22341 22341 E DevLauncher: 	at android.os.Looper.loop(Looper.java:319)
09-25 10:24:33.201 22341 22341 E DevLauncher: 	at android.app.ActivityThread.main(ActivityThread.java:8919)
09-25 10:24:33.201 22341 22341 E DevLauncher: 	at java.lang.reflect.Method.invoke(Native Method)
09-25 10:24:33.201 22341 22341 E DevLauncher: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
09-25 10:24:33.201 22341 22341 E DevLauncher: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by DTupalov** [comment]
> Hello, I see the same error in my Android vitals. I'm using RN 0.74.0 and rnMapbox 10.1.29.
> 
> Maybe this trace can help too:
> 
> ```
> Exception java.lang.NullPointerException:
>   at com.rnmapbox.rnmbx.components.camera.CameraUpdateQueue.execute (CameraUpdateQueue.kt:62)
>   at com.rnmapbox.rnmbx.components.camera.RNMBXCamera.updateCamera (RNMBXCamera.kt:205)
>   at com.rnmapbox.rnmbx.components.camera.RNMBXCamera.access$setHasSentFirstRegion$p (RNMBXCamera.kt:41)
>   at com.rnmapbox.rnmbx.components.camera.RNMBXCamera.access$updateCamera (RNMBXCamera.kt:41)
>   at com.rnmapbox.rnmbx.components.camera.RNMBXCamera$addToMap$1.invoke (RNMBXCamera.kt:104)
>   at com.rnmapbox.rnmbx.components.camera.RNMBXCamera$addToMap$1.invoke (RNMBXCamera.kt:101)
>   at com.rnmapbox.rnmbx.components.mapview.RNMBXLifeCycle.afterAttachFromLooper (RNMBXMapView.kt:178)
>   at com.rnmapbox.rnmbx.components.mapview.RNMBXMapView.onAttachedToWindow$lambda$26 (RNMBXMapView.kt:1479)
>   at android.os.Handler.handleCallback (Handler.java:958)
>   at android.os.Handler.dispatchMessage (Handler.java:99)
>   at android.os.Looper.loopOnce (Looper.java:230)
>   at android.os.Looper.loop (Looper.java:319)
>   at android.app.ActivityThread.main (ActivityThread.java:8918)
>   at java.lang.reflect.Method.invoke
>   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:608)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1103)
> ```
> 
> Any clue ?

I have the same problem. Got it in Crashlytics

```
Device
Brand:Xiaomi
Model:Poco M5
Orientation:Portrait
RAM free: 1.79 GB
Disk free: 71.3 GB
Operating System
Version:Android 14
Orientation:Portrait
Rooted: No
```

**Comment by DTupalov** [comment]
> > Hello, I see the same error in my Android vitals. I'm using RN 0.74.0 and rnMapbox 10.1.29.
> > Maybe this trace can help too:
> > ```
> > Exception java.lang.NullPointerException:
> >   at com.rnmapbox.rnmbx.components.camera.CameraUpdateQueue.execute (CameraUpdateQueue.kt:62)
> >   at com.rnmapbox.rnmbx.components.camera.RNMBXCamera.updateCamera (RNMBXCamera.kt:205)
> >   at com.rnmapbox.rnmbx.components.camera.RNMBXCamera.access$setHasSentFirstRegion$p (RNMBXCamera.kt:41)
> >   at com.rnmapbox.rnmbx.components.camera.RNMBXCamera.access$updateCamera (RNMBXCamera.kt:41)
> >   at com.rnmapbox.rnmbx.components.camera.RNMBXCamera$addToMap$1.invoke (RNMBXCamera.kt:104)
> >   at com.rnmapbox.rnmbx.components.camera.RNMBXCamera$addToMap$1.invoke (RNMBXCamera.kt:101)
> >   at com.rnmapbox.rnmbx.components.mapview.RNMBXLifeCycle.afterAttachFromLooper (RNMBXMapView.kt:178)
> >   at com.rnmapbox.rnmbx.components.mapview.RNMBXMapView.onAttachedToWindow$lambda$26 (RNMBXMapView.kt:1479)
> >   at android.os.Handler.handleCallback (Handler.java:958)
> >   at android.os.Handler.dispatchMessage (Handler.java:99)
> >   at android.os.Looper.loopOnce (Looper.java:230)
> >   at android.os.Looper.loop (Looper.java:319)
> >   at android.app.ActivityThread.main (ActivityThread.java:8918)
> >   at java.lang.reflect.Method.invoke
> >   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:608)
> >   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1103)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any clue ?
> 
> I have the same problem. Got it in Crashlytics
> 
> ```
> Device
> Brand:Xiaomi
> Model:Poco M5
> Orientation:Portrait
> RAM free: 1.79 GB
> Disk free: 71.3 GB
> Operating System
> Version:Android 14
> Orientation:Portrait
> Rooted: No
> ```

And one more crash on other phone

```
Fatal Exception: java.lang.NullPointerException:
       at com.rnmapbox.rnmbx.components.camera.CameraUpdateQueue.execute(CameraUpdateQueue.kt:62)
       at com.rnmapbox.rnmbx.components.camera.RNMBXCamera.updateCamera(RNMBXCamera.kt:205)
       at com.rnmapbox.rnmbx.components.camera.RNMBXCamera.access$updateCamera(RNMBXCamera.kt:41)
       at com.rnmapbox.rnmbx.components.camera.RNMBXCamera$addToMap$1.invoke(RNMBXCamera.kt:104)
       at com.rnmapbox.rnmbx.components.camera.RNMBXCamera$addToMap$1.invoke(RNMBXCamera.kt:101)
       at com.rnmapbox.rnmbx.components.mapview.RNMBXLifeCycle.afterAttachFromLooper(RNMBXMapView.kt:178)
       at com.rnmapbox.rnmbx.components.mapview.RNMBXMapView.onAttachedToWindow$lambda$26(RNMBXMapView.kt:1477)
       at com.rnmapbox.rnmbx.components.mapview.RNMBXMapView.$r8$lambda$5oEp4uR9fWYfY6VAbOGSD-HxZi0()
       at com.rnmapbox.rnmbx.components.mapview.RNMBXMapView$$ExternalSyntheticLambda6.run(:2)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8919)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```
Phone info

```
Device
Brand:Samsung
Model:Galaxy S21 Ultra 5G
Orientation:Portrait
RAM free: 5.25 GB
Disk free: 64.97 GB
Operating System
Version:Android 14
Orientation:Portrait
Rooted: No
```

App info
```
System:
  OS: macOS 14.6.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 105.11 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.13.1
    path: ~/.nvm/versions/node/v20.13.1/bin/node
  Yarn:
    version: 1.22.22
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.5.2
    path: ~/.nvm/versions/node/v20.13.1/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/dtupalov/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK:
    API Levels:
      - "33"
      - "34"
      - "35"
    Build Tools:
      - 33.0.1
      - 34.0.0
      - 35.0.0
    System Images:
      - android-28 | Google APIs ARM 64 v8a
      - android-31 | Google APIs ARM 64 v8a
      - android-31 | Google Play ARM 64 v8a
      - android-32 | Google APIs ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
      - android-35 | Google APIs ARM 64 v8a
      - android-35 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12071903
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/dtupalov/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native:
    installed: 0.73.7
    wanted: "*"
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

Mapbox version
```
 "@rnmapbox/maps": "^10.1.21"
```

And I can reproduce it on my production App, but need to repeat 3-5 times

1. Open app
2. Grant location permission AND notification permission (without it I didn't catch this problem) 
3. Close app
4. Remove permissions for location and notification
5. Open app (on this step app can crash, with error above)

If crash didn't happen, try 1-5 steps more and more, while app will down with fatal error.

**Comment by Hosam-hsm** [comment]
Facing this issue with "@rnmapbox/maps": "10.1.36", "expo": "^52.0.39" and RNMapboxMapsVersion: "11.10.1"

Fatal
—
NullPointerException ViewTagResolver.kt getManager com.rnmapbox.rnmbx.utils.ViewTagResolver in getManager

**Comment by DavidAmyot** [comment]
+1 Same issue with latest expo sdk 53 and latest v11 of rnmapbox, first appeared for us in production.

**Comment by DylanFeelbat** [comment]
A note for anyone who lands here from a search for `ViewTagResolver` + `NullPointerException`, because there are **two different causes** behind this one stack frame and the fix differs.

**The cause reported in this thread** looks like a torn-down Catalyst instance. @nixolas1's log is the clearest evidence — the soft exception right above the NPE says:

```
ReactNoCrashSoftException: Cannot get UIManager because the context
doesn't contain an active CatalystInstance
```

That matches the other reports here: intermittent, on dev-server reload or on resuming from the background. `UIManagerHelper.getUIManager` legitimately returns null once the instance is gone.

**A second, unrelated cause** — which is what brought me here, and which is *deterministic on every `MapView` mount* rather than intermittent:

`ViewTagResolver` gained a hardcoded `UIManagerType.FABRIC` in **10.3.0**. Before that it branched:

```kotlin
// 10.2.x
get() = if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
    UIManagerHelper.getUIManager(context, UIManagerType.FABRIC)!!
} else {
    UIManagerHelper.getUIManager(context, UIManagerType.DEFAULT)!!
}
```

On an app built with `newArchEnabled=false`, Fabric is not installed, so on 10.3.x the FABRIC lookup returns null and the `!!` throws on every mount. This is *not* a bug — 10.3.0 onwards only supports the new architecture (#4128 is explicit about it) and 10.3.2 declares `react-native >=0.79`. It is simply what an unsupported configuration looks like from the outside, and it is easy to reach by accident: a `^10.2.x` range in `package.json` resolves to 10.3.x and silently crosses that boundary.

So if your crash is **deterministic on every map mount** and you are on 10.3.x with the old architecture, this thread's discussion does not apply to you — pin to `~10.2.10` (last release with the branch above, peer range `react-native >=0.69`) or move to the new architecture. If your crash is **intermittent around reloads or resume**, it is the issue actually being tracked here.

---

One observation that spans both, in case it is useful: `UIManagerHelper.getUIManager` is `@Nullable`, and both causes are the same `!!` on its result — the difference is only *why* it was null. The null case is reachable on the new architecture too, since a dead Catalyst instance has no Fabric UIManager either, so handling it would still be worthwhile after the old-arch removal. Happy to open a PR if that would be welcome.
