### ISSUE TITLE
[Bug]: Task :app:checkDebugDuplicateClasses FAILED

### ISSUE THREAD

**Issue by i1kaaasra** [rnmapbox/maps#3417]
### Mapbox Implementation

Mapbox

### Mapbox Version

11.2.0

### React Native Version

0.73.2

### Platform

Android

### `@rnmapbox/maps` version

10.1.19

### Standalone component to reproduce

```
Task :app:checkDebugDuplicateClasses FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.mapbox.geojson.BaseCoordinatesTypeAdapter found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.BaseGeometryTypeAdapter found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.BoundingBox found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.CoordinateContainer found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.Feature found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.Feature$GsonTypeAdapter found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.FeatureCollection found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.FeatureCollection$GsonTypeAdapter found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.GeoJson found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.Geometry found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.GeometryAdapterFactory found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.GeometryCollection found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.GeometryCollection$GsonTypeAdapter found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.LineString found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.LineString$GsonTypeAdapter found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.ListOfDoublesCoordinatesTypeAdapter found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.ListOfListOfPointCoordinatesTypeAdapter found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.ListOfPointCoordinatesTypeAdapter found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.ListofListofListOfPointCoordinatesTypeAdapter found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.MultiLineString found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.MultiLineString$GsonTypeAdapter found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.MultiPoint found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.MultiPoint$GsonTypeAdapter found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.MultiPolygon found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.MultiPolygon$GsonTypeAdapter found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.Point found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.Point$GsonTypeAdapter found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.PointAsCoordinatesTypeAdapter found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.Polygon found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.Polygon$GsonTypeAdapter found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.constants.GeoJsonConstants found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.exception.GeoJsonException found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.gson.BoundingBoxTypeAdapter found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.gson.GeoJsonAdapterFactory found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.gson.GeoJsonAdapterFactory$GeoJsonAdapterFactoryIml found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.gson.GeometryGeoJson found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.internal.typeadapters.RuntimeTypeAdapterFactory found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.internal.typeadapters.RuntimeTypeAdapterFactory$1 found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.shifter.CoordinateShifter found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.shifter.CoordinateShifterManager found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.shifter.CoordinateShifterManager$1 found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.utils.GeoJsonUtils found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.geojson.utils.PolylineUtils found in modules jetified-android-sdk-geojson-5.9.0 (org.maplibre.gl:android-sdk-geojson:5.9.0) and jetified-mapbox-sdk-geojson-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-geojson:6.11.0)
     Duplicate class com.mapbox.turf.TurfAssertions found in modules jetified-android-sdk-turf-5.9.0 (org.maplibre.gl:android-sdk-turf:5.9.0) and jetified-mapbox-sdk-turf-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-turf:6.11.0)
     Duplicate class com.mapbox.turf.TurfClassification found in modules jetified-android-sdk-turf-5.9.0 (org.maplibre.gl:android-sdk-turf:5.9.0) and jetified-mapbox-sdk-turf-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-turf:6.11.0)
     Duplicate class com.mapbox.turf.TurfConstants found in modules jetified-android-sdk-turf-5.9.0 (org.maplibre.gl:android-sdk-turf:5.9.0) and jetified-mapbox-sdk-turf-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-turf:6.11.0)
     Duplicate class com.mapbox.turf.TurfConstants$TurfUnitCriteria found in modules jetified-android-sdk-turf-5.9.0 (org.maplibre.gl:android-sdk-turf:5.9.0) and jetified-mapbox-sdk-turf-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-turf:6.11.0)
     Duplicate class com.mapbox.turf.TurfConversion found in modules jetified-android-sdk-turf-5.9.0 (org.maplibre.gl:android-sdk-turf:5.9.0) and jetified-mapbox-sdk-turf-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-turf:6.11.0)
     Duplicate class com.mapbox.turf.TurfException found in modules jetified-android-sdk-turf-5.9.0 (org.maplibre.gl:android-sdk-turf:5.9.0) and jetified-mapbox-sdk-turf-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-turf:6.11.0)
     Duplicate class com.mapbox.turf.TurfJoins found in modules jetified-android-sdk-turf-5.9.0 (org.maplibre.gl:android-sdk-turf:5.9.0) and jetified-mapbox-sdk-turf-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-turf:6.11.0)
     Duplicate class com.mapbox.turf.TurfMeasurement found in modules jetified-android-sdk-turf-5.9.0 (org.maplibre.gl:android-sdk-turf:5.9.0) and jetified-mapbox-sdk-turf-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-turf:6.11.0)
     Duplicate class com.mapbox.turf.TurfMeta found in modules jetified-android-sdk-turf-5.9.0 (org.maplibre.gl:android-sdk-turf:5.9.0) and jetified-mapbox-sdk-turf-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-turf:6.11.0)
     Duplicate class com.mapbox.turf.TurfMisc found in modules jetified-android-sdk-turf-5.9.0 (org.maplibre.gl:android-sdk-turf:5.9.0) and jetified-mapbox-sdk-turf-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-turf:6.11.0)
     Duplicate class com.mapbox.turf.TurfTransformation found in modules jetified-android-sdk-turf-5.9.0 (org.maplibre.gl:android-sdk-turf:5.9.0) and jetified-mapbox-sdk-turf-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-turf:6.11.0)
     Duplicate class com.mapbox.turf.models.LineIntersectsResult found in modules jetified-android-sdk-turf-5.9.0 (org.maplibre.gl:android-sdk-turf:5.9.0) and jetified-mapbox-sdk-turf-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-turf:6.11.0)
     Duplicate class com.mapbox.turf.models.LineIntersectsResult$1 found in modules jetified-android-sdk-turf-5.9.0 (org.maplibre.gl:android-sdk-turf:5.9.0) and jetified-mapbox-sdk-turf-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-turf:6.11.0)
     Duplicate class com.mapbox.turf.models.LineIntersectsResult$Builder found in modules jetified-android-sdk-turf-5.9.0 (org.maplibre.gl:android-sdk-turf:5.9.0) and jetified-mapbox-sdk-turf-6.11.0 (com.mapbox.mapboxsdk:mapbox-sdk-turf:6.11.0)
     
     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 25s
462 actionable tasks: 22 executed, 3 from cache, 437 up-to-date
Error: /Users/ikaaasra/Desktop/CLIENT/hamipeyk/android/gradlew exited with non-zero code: 1
Error: /Users/ikaaasra/Desktop/CLIENT/hamipeyk/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/ikaaasra/Desktop/CLIENT/hamipeyk/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:634:26)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at Object.spawnAsync [as default] (/Users/ikaaasra/Desktop/CLIENT/hamipeyk/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnGradleAsync (/Users/ikaaasra/Desktop/CLIENT/hamipeyk/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:72:46)
    at Object.assembleAsync (/Users/ikaaasra/Desktop/CLIENT/hamipeyk/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:52:18)
    at runAndroidAsync (/Users/ikaaasra/Desktop/CLIENT/hamipeyk/node_modules/@expo/cli/build/src/run/android/runAndroidAsync.js:36:24
```

**Comment by i1kaaasra** [comment]
```
import React from 'react';
import { StyleSheet, View } from 'react-native';
import Mapbox from '@rnmapbox/maps';

Mapbox.setAccessToken('<YOUR_ACCESSTOKEN>');

const App = () => {
  return (
    <View style={styles.page}>
      <View style={styles.container}>
        <Mapbox.MapView style={styles.map} />
      </View>
    </View>
  );
}

export default App;

const styles = StyleSheet.create({
  page: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {
    height: 300,
    width: 300,
  },
  map: {
    flex: 1
  }
});
```

**Comment by i1kaaasra** [comment]
why ???

**Comment by mfazekas** [comment]
FWIW @rnmapbox/maps 10.1 doesn't support maplibre, not sure why you have that linked to your app
